// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="depthwise_depthwise,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.912000,HLS_SYN_LAT=5604,HLS_SYN_TPT=none,HLS_SYN_MEM=68,HLS_SYN_DSP=0,HLS_SYN_FF=2054,HLS_SYN_LUT=2043,HLS_VERSION=2020_2}" *)

module depthwise (
        ap_clk,
        ap_rst_n,
        strm_in_TDATA,
        strm_in_TVALID,
        strm_in_TREADY,
        strm_in_TKEEP,
        strm_in_TSTRB,
        strm_in_TLAST,
        strm_out_TDATA,
        strm_out_TVALID,
        strm_out_TREADY,
        strm_out_TKEEP,
        strm_out_TSTRB,
        strm_out_TLAST,
        kernelN,
        kernelSize,
        mapSizeX,
        mapSizeY,
        relu
);

parameter    ap_ST_fsm_state1 = 29'd1;
parameter    ap_ST_fsm_state2 = 29'd2;
parameter    ap_ST_fsm_state3 = 29'd4;
parameter    ap_ST_fsm_state4 = 29'd8;
parameter    ap_ST_fsm_state5 = 29'd16;
parameter    ap_ST_fsm_state6 = 29'd32;
parameter    ap_ST_fsm_state7 = 29'd64;
parameter    ap_ST_fsm_pp1_stage0 = 29'd128;
parameter    ap_ST_fsm_state14 = 29'd256;
parameter    ap_ST_fsm_state15 = 29'd512;
parameter    ap_ST_fsm_state16 = 29'd1024;
parameter    ap_ST_fsm_state17 = 29'd2048;
parameter    ap_ST_fsm_state18 = 29'd4096;
parameter    ap_ST_fsm_state19 = 29'd8192;
parameter    ap_ST_fsm_state20 = 29'd16384;
parameter    ap_ST_fsm_state21 = 29'd32768;
parameter    ap_ST_fsm_state22 = 29'd65536;
parameter    ap_ST_fsm_state23 = 29'd131072;
parameter    ap_ST_fsm_state24 = 29'd262144;
parameter    ap_ST_fsm_state25 = 29'd524288;
parameter    ap_ST_fsm_state26 = 29'd1048576;
parameter    ap_ST_fsm_state27 = 29'd2097152;
parameter    ap_ST_fsm_state28 = 29'd4194304;
parameter    ap_ST_fsm_state29 = 29'd8388608;
parameter    ap_ST_fsm_state30 = 29'd16777216;
parameter    ap_ST_fsm_state31 = 29'd33554432;
parameter    ap_ST_fsm_state32 = 29'd67108864;
parameter    ap_ST_fsm_state33 = 29'd134217728;
parameter    ap_ST_fsm_state34 = 29'd268435456;

input   ap_clk;
input   ap_rst_n;
input  [31:0] strm_in_TDATA;
input   strm_in_TVALID;
output   strm_in_TREADY;
input  [3:0] strm_in_TKEEP;
input  [3:0] strm_in_TSTRB;
input  [0:0] strm_in_TLAST;
output  [31:0] strm_out_TDATA;
output   strm_out_TVALID;
input   strm_out_TREADY;
output  [3:0] strm_out_TKEEP;
output  [3:0] strm_out_TSTRB;
output  [0:0] strm_out_TLAST;
input  [31:0] kernelN;
input  [31:0] kernelSize;
input  [31:0] mapSizeX;
input  [31:0] mapSizeY;
input   relu;

 reg    ap_rst_n_inv;
reg    strm_in_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [28:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln51_fu_840_p2;
wire   [0:0] icmp_ln54_fu_846_p2;
wire   [0:0] icmp_ln55_fu_851_p2;
wire   [0:0] icmp_ln56_fu_856_p2;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter0;
wire    ap_block_pp1_stage0;
wire   [0:0] icmp_ln70_fu_978_p2;
wire   [0:0] icmp_ln73_fu_984_p2;
wire   [0:0] icmp_ln74_fu_989_p2;
wire    ap_CS_fsm_state33;
reg   [0:0] icmp_ln113_reg_1677;
reg    strm_out_TDATA_blk_n;
reg   [0:0] icmp_ln107_1_reg_1595;
wire    ap_CS_fsm_state34;
reg   [0:0] icmp_ln101_reg_1575;
reg   [0:0] icmp_ln102_reg_1579;
reg   [0:0] icmp_ln103_reg_1583;
reg   [0:0] icmp_ln104_reg_1587;
reg   [0:0] icmp_ln105_reg_1591;
reg   [0:0] and_ln112_reg_1673;
reg   [31:0] x_4_reg_401;
reg  signed [31:0] n_5_reg_412;
reg   [31:0] x_9_reg_424;
wire  signed [13:0] empty_fu_798_p1;
reg  signed [13:0] empty_reg_1396;
wire   [15:0] empty_21_fu_802_p1;
reg   [15:0] empty_21_reg_1402;
wire   [15:0] empty_22_fu_806_p1;
reg   [15:0] empty_22_reg_1407;
wire   [15:0] empty_23_fu_810_p1;
reg   [15:0] empty_23_reg_1413;
reg   [31:0] tmp_data_V_reg_1418;
wire  signed [17:0] empty_25_fu_825_p1;
reg  signed [17:0] empty_25_reg_1426;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln47_fu_819_p2;
wire   [0:0] icmp_ln49_fu_828_p2;
wire    ap_CS_fsm_state3;
wire   [31:0] n_4_fu_834_p2;
wire   [31:0] x_6_fu_885_p2;
reg    ap_predicate_op105_read_state4;
reg    ap_block_state4;
wire   [31:0] y_5_fu_891_p2;
wire    ap_CS_fsm_state5;
wire   [1:0] y_6_fu_897_p2;
reg   [1:0] y_6_reg_1464;
wire    ap_CS_fsm_state6;
wire   [17:0] zext_ln67_fu_909_p1;
reg   [17:0] zext_ln67_reg_1472;
wire   [0:0] icmp_ln67_fu_903_p2;
wire  signed [31:0] conv48_fu_936_p1;
reg  signed [31:0] conv48_reg_1484;
wire  signed [31:0] conv59_fu_944_p1;
reg  signed [31:0] conv59_reg_1489;
wire  signed [7:0] accum_V_5_fu_948_p1;
reg  signed [7:0] accum_V_5_reg_1494;
wire  signed [31:0] sext_ln87_fu_958_p1;
reg  signed [31:0] sext_ln87_reg_1499;
wire   [0:0] icmp_ln68_fu_972_p2;
wire    ap_CS_fsm_state7;
reg   [0:0] icmp_ln70_reg_1508;
reg    ap_predicate_op158_read_state8;
reg    ap_block_state8_pp1_stage0_iter0;
wire    ap_block_state9_pp1_stage0_iter1;
wire    ap_block_state10_pp1_stage0_iter2;
wire    ap_block_state11_pp1_stage0_iter3;
wire    ap_block_state12_pp1_stage0_iter4;
wire    ap_block_state13_pp1_stage0_iter5;
reg    ap_block_pp1_stage0_11001;
reg   [0:0] icmp_ln70_reg_1508_pp1_iter1_reg;
reg   [0:0] icmp_ln70_reg_1508_pp1_iter2_reg;
reg   [0:0] icmp_ln70_reg_1508_pp1_iter3_reg;
reg   [0:0] icmp_ln70_reg_1508_pp1_iter4_reg;
reg   [0:0] icmp_ln73_reg_1512;
reg   [0:0] icmp_ln73_reg_1512_pp1_iter1_reg;
reg   [0:0] icmp_ln73_reg_1512_pp1_iter2_reg;
reg   [0:0] icmp_ln73_reg_1512_pp1_iter3_reg;
reg   [0:0] icmp_ln73_reg_1512_pp1_iter4_reg;
reg   [0:0] icmp_ln74_reg_1516;
reg   [0:0] icmp_ln74_reg_1516_pp1_iter1_reg;
reg   [0:0] icmp_ln74_reg_1516_pp1_iter2_reg;
reg   [0:0] icmp_ln74_reg_1516_pp1_iter3_reg;
reg   [0:0] icmp_ln74_reg_1516_pp1_iter4_reg;
wire   [3:0] trunc_ln69_2_fu_994_p1;
reg   [3:0] trunc_ln69_2_reg_1520;
reg   [3:0] trunc_ln69_2_reg_1520_pp1_iter1_reg;
reg   [3:0] trunc_ln69_2_reg_1520_pp1_iter2_reg;
reg   [3:0] trunc_ln69_2_reg_1520_pp1_iter3_reg;
reg   [3:0] trunc_ln69_2_reg_1520_pp1_iter4_reg;
wire   [31:0] n_7_fu_1003_p2;
reg   [31:0] n_7_reg_1525;
wire   [17:0] trunc_ln70_fu_1009_p1;
reg   [17:0] trunc_ln70_reg_1530;
reg   [17:0] trunc_ln70_reg_1530_pp1_iter2_reg;
reg   [17:0] trunc_ln70_reg_1530_pp1_iter3_reg;
wire   [17:0] empty_28_fu_1013_p1;
reg   [17:0] empty_28_reg_1535;
wire   [31:0] x_5_fu_1021_p2;
wire    ap_CS_fsm_state14;
wire   [31:0] y_8_fu_1059_p2;
wire    ap_CS_fsm_state16;
wire   [0:0] icmp_ln89_fu_1053_p2;
wire   [31:0] x_8_fu_1071_p2;
wire    ap_CS_fsm_state17;
wire   [0:0] icmp_ln91_fu_1065_p2;
wire   [31:0] kn_3_fu_1083_p2;
wire    ap_CS_fsm_state18;
wire   [0:0] icmp_ln94_fu_1077_p2;
wire   [0:0] icmp_ln101_fu_1095_p2;
wire    ap_CS_fsm_state19;
wire   [0:0] icmp_ln97_fu_1089_p2;
wire   [0:0] icmp_ln102_fu_1100_p2;
wire   [0:0] icmp_ln103_fu_1105_p2;
wire   [0:0] icmp_ln104_fu_1110_p2;
wire   [0:0] icmp_ln105_fu_1115_p2;
wire   [0:0] icmp_ln107_1_fu_1120_p2;
wire   [31:0] ky_2_fu_1130_p2;
wire   [17:0] trunc_ln109_fu_1136_p1;
reg   [17:0] trunc_ln109_reg_1606;
wire    ap_CS_fsm_state20;
wire   [1:0] trunc_ln36_fu_1144_p1;
reg   [1:0] trunc_ln36_reg_1617;
wire    ap_CS_fsm_state22;
wire   [17:0] trunc_ln36_2_fu_1166_p1;
reg   [17:0] trunc_ln36_2_reg_1622;
wire    ap_CS_fsm_state24;
wire  signed [17:0] grp_fu_1321_p4;
reg  signed [17:0] add_ln109_1_reg_1628;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state29;
wire   [7:0] accum_V_4_fu_1227_p3;
reg   [7:0] accum_V_4_reg_1666;
wire    ap_CS_fsm_state30;
wire   [0:0] and_ln112_fu_1245_p2;
wire   [0:0] icmp_ln113_fu_1251_p2;
wire   [31:0] kx_2_fu_1303_p2;
reg    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state8;
reg    ap_enable_reg_pp1_iter1;
reg    ap_enable_reg_pp1_iter2;
reg    ap_enable_reg_pp1_iter3;
reg    ap_enable_reg_pp1_iter4;
reg    ap_enable_reg_pp1_iter5;
reg   [13:0] filter_V_address0;
reg    filter_V_ce0;
reg    filter_V_we0;
wire   [3:0] filter_V_d0;
wire  signed [3:0] filter_V_q0;
reg   [17:0] featureMap_V_address0;
reg    featureMap_V_ce0;
reg    featureMap_V_we0;
reg   [3:0] featureMap_V_d0;
wire  signed [3:0] featureMap_V_q0;
reg   [31:0] n_reg_254;
reg   [31:0] y_reg_266;
reg   [31:0] n_1_reg_278;
reg   [31:0] n_2_reg_311;
reg   [31:0] x_reg_289;
reg   [31:0] y_1_reg_300;
reg   [31:0] ap_phi_mux_y_3_phi_fu_344_p8;
reg   [31:0] ap_phi_mux_n_3_phi_fu_363_p8;
reg   [31:0] ap_phi_mux_x_3_phi_fu_326_p8;
reg   [1:0] y_2_reg_378;
reg   [31:0] x_1_reg_389;
reg   [31:0] ap_phi_mux_x_4_phi_fu_404_p4;
reg  signed [31:0] ap_phi_mux_n_5_phi_fu_416_p4;
wire   [31:0] ap_phi_reg_pp1_iter0_x_9_reg_424;
reg   [31:0] ap_phi_mux_n_6_phi_fu_443_p6;
wire   [31:0] ap_phi_reg_pp1_iter0_n_6_reg_440;
reg   [31:0] y_4_reg_454;
reg   [31:0] y_7_reg_466;
wire    ap_CS_fsm_state15;
wire    regslice_both_strm_out_V_data_V_U_apdone_blk;
wire   [0:0] icmp_ln87_fu_1037_p2;
reg   [31:0] x_2_reg_477;
reg   [31:0] y_9_reg_489;
reg   [31:0] x_7_reg_501;
reg   [31:0] kn_reg_512;
reg   [31:0] y_10_reg_524;
wire   [31:0] ap_phi_mux_y_11_phi_fu_575_p4;
reg   [31:0] x_10_reg_536;
wire   [31:0] ap_phi_mux_x_11_phi_fu_587_p4;
reg   [31:0] kn_1_reg_548;
wire  signed [31:0] ap_phi_mux_kn_2_phi_fu_599_p4;
reg   [31:0] ky_reg_559;
reg   [31:0] y_11_reg_571;
reg   [31:0] ap_phi_mux_y_12_phi_fu_635_p16;
reg    ap_predicate_op328_write_state34;
reg    ap_block_state34;
reg    ap_block_state34_io;
reg   [31:0] x_11_reg_583;
reg   [31:0] ap_phi_mux_x_12_phi_fu_667_p16;
reg  signed [31:0] kn_2_reg_595;
reg   [31:0] ap_phi_mux_kn_4_phi_fu_699_p16;
wire   [31:0] ap_phi_mux_ky_1_phi_fu_610_p4;
reg   [31:0] ky_1_reg_607;
reg   [31:0] ap_phi_mux_ky_3_phi_fu_732_p16;
wire   [31:0] ap_phi_mux_kx_phi_fu_622_p4;
reg   [31:0] kx_reg_618;
reg   [31:0] y_12_reg_630;
reg    ap_block_state33;
reg    ap_block_state33_io;
reg   [31:0] x_12_reg_662;
reg   [31:0] kn_4_reg_694;
reg   [31:0] ky_3_reg_726;
reg   [31:0] ap_phi_mux_kx_1_phi_fu_764_p16;
reg   [31:0] kx_1_reg_759;
wire   [63:0] zext_ln59_fu_875_p1;
wire   [63:0] zext_ln77_fu_1017_p1;
wire   [63:0] zext_ln109_fu_1183_p1;
wire   [63:0] zext_ln109_1_fu_1188_p1;
wire   [63:0] zext_ln116_fu_1270_p1;
reg   [31:0] count_fu_132;
wire   [31:0] count_1_fu_869_p2;
reg   [7:0] accum_V_fu_144;
wire  signed [7:0] accum_V_7_fu_1286_p3;
wire   [3:0] trunc_ln69_fu_1265_p1;
wire  signed [31:0] empty_23_fu_810_p0;
wire   [15:0] sub_ln84_fu_916_p2;
wire   [15:0] sub_ln85_fu_926_p2;
wire  signed [15:0] outMapYSize_fu_920_p2;
wire   [15:0] outMapXSize_fu_930_p2;
wire   [3:0] bias_V_fu_913_p1;
wire  signed [16:0] outMapYSize_cast_fu_940_p1;
wire   [16:0] sub81_fu_952_p2;
wire   [21:0] tmp_2_fu_962_p4;
wire   [31:0] grp_fu_998_p2;
wire  signed [17:0] grp_fu_1309_p4;
wire   [21:0] tmp_1_fu_1027_p4;
wire   [21:0] tmp_3_fu_1043_p4;
wire   [31:0] grp_fu_1125_p2;
wire   [1:0] trunc_ln36_1_fu_1148_p1;
wire   [1:0] add_ln109_fu_1152_p2;
wire    ap_CS_fsm_state23;
wire   [17:0] trunc_ln36_3_fu_1174_p1;
(* use_dsp48 = "no" *) wire   [17:0] add_ln109_2_fu_1178_p2;
wire  signed [13:0] grp_fu_1329_p4;
wire   [31:0] or_ln107_fu_1203_p2;
wire   [0:0] icmp_ln107_fu_1209_p2;
wire   [0:0] and_ln107_fu_1215_p2;
wire  signed [7:0] grp_fu_1339_p3;
wire   [0:0] icmp_ln112_fu_1233_p2;
wire   [0:0] icmp_ln112_1_fu_1239_p2;
wire   [1:0] add_ln116_fu_1256_p2;
wire  signed [17:0] grp_fu_1348_p4;
wire   [0:0] tmp_4_fu_1274_p3;
wire   [0:0] and_ln120_fu_1281_p1;
wire   [0:0] and_ln120_fu_1281_p2;
wire   [1:0] grp_fu_1309_p1;
wire  signed [13:0] grp_fu_1316_p0;
wire   [1:0] grp_fu_1321_p0;
wire   [17:0] grp_fu_1321_p3;
wire  signed [13:0] grp_fu_1316_p2;
wire   [13:0] grp_fu_1329_p1;
wire   [13:0] grp_fu_1329_p3;
wire   [7:0] grp_fu_1339_p2;
wire   [1:0] grp_fu_1348_p1;
wire    ap_CS_fsm_state32;
reg    grp_fu_998_ce;
reg    grp_fu_1309_ce;
reg    grp_fu_1348_ce;
wire    ap_CS_fsm_state31;
reg   [28:0] ap_NS_fsm;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
wire    regslice_both_strm_in_V_data_V_U_apdone_blk;
wire   [31:0] strm_in_TDATA_int_regslice;
wire    strm_in_TVALID_int_regslice;
reg    strm_in_TREADY_int_regslice;
wire    regslice_both_strm_in_V_data_V_U_ack_in;
wire    regslice_both_strm_in_V_keep_V_U_apdone_blk;
wire   [3:0] strm_in_TKEEP_int_regslice;
wire    regslice_both_strm_in_V_keep_V_U_vld_out;
wire    regslice_both_strm_in_V_keep_V_U_ack_in;
wire    regslice_both_strm_in_V_strb_V_U_apdone_blk;
wire   [3:0] strm_in_TSTRB_int_regslice;
wire    regslice_both_strm_in_V_strb_V_U_vld_out;
wire    regslice_both_strm_in_V_strb_V_U_ack_in;
wire    regslice_both_strm_in_V_last_V_U_apdone_blk;
wire   [0:0] strm_in_TLAST_int_regslice;
wire    regslice_both_strm_in_V_last_V_U_vld_out;
wire    regslice_both_strm_in_V_last_V_U_ack_in;
wire   [31:0] strm_out_TDATA_int_regslice;
reg    strm_out_TVALID_int_regslice;
wire    strm_out_TREADY_int_regslice;
wire    regslice_both_strm_out_V_data_V_U_vld_out;
wire    regslice_both_strm_out_V_keep_V_U_apdone_blk;
wire    regslice_both_strm_out_V_keep_V_U_ack_in_dummy;
wire    regslice_both_strm_out_V_keep_V_U_vld_out;
wire    regslice_both_strm_out_V_strb_V_U_apdone_blk;
wire    regslice_both_strm_out_V_strb_V_U_ack_in_dummy;
wire    regslice_both_strm_out_V_strb_V_U_vld_out;
wire    regslice_both_strm_out_V_last_V_U_apdone_blk;
wire    regslice_both_strm_out_V_last_V_U_ack_in_dummy;
wire    regslice_both_strm_out_V_last_V_U_vld_out;
wire   [17:0] grp_fu_1321_p00;
wire   [17:0] grp_fu_1348_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 29'd1;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 ap_enable_reg_pp1_iter4 = 1'b0;
#0 ap_enable_reg_pp1_iter5 = 1'b0;
end

depthwise_filter_V #(
    .DataWidth( 4 ),
    .AddressRange( 13824 ),
    .AddressWidth( 14 ))
filter_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(filter_V_address0),
    .ce0(filter_V_ce0),
    .we0(filter_V_we0),
    .d0(filter_V_d0),
    .q0(filter_V_q0)
);

depthwise_featureMap_V #(
    .DataWidth( 4 ),
    .AddressRange( 258048 ),
    .AddressWidth( 18 ))
featureMap_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(featureMap_V_address0),
    .ce0(featureMap_V_ce0),
    .we0(featureMap_V_we0),
    .d0(featureMap_V_d0),
    .q0(featureMap_V_q0)
);

depthwise_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(ap_phi_mux_n_5_phi_fu_416_p4),
    .din1(mapSizeY),
    .ce(grp_fu_998_ce),
    .dout(grp_fu_998_p2)
);

depthwise_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(kn_2_reg_595),
    .din1(mapSizeY),
    .ce(1'b1),
    .dout(grp_fu_1125_p2)
);

depthwise_ama_addmuladd_18ns_2ns_18s_18ns_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 18 ),
    .din3_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
ama_addmuladd_18ns_2ns_18s_18ns_18_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(empty_28_reg_1535),
    .din1(grp_fu_1309_p1),
    .din2(empty_25_reg_1426),
    .din3(trunc_ln70_reg_1530_pp1_iter3_reg),
    .ce(grp_fu_1309_ce),
    .dout(grp_fu_1309_p4)
);

depthwise_mul_mul_14s_14s_14_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 14 ))
mul_mul_14s_14s_14_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_1316_p0),
    .din1(empty_reg_1396),
    .ce(1'b1),
    .dout(grp_fu_1316_p2)
);

depthwise_ama_addmuladd_2ns_18ns_18s_18ns_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 18 ),
    .din3_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
ama_addmuladd_2ns_18ns_18s_18ns_18_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_1321_p0),
    .din1(trunc_ln109_reg_1606),
    .din2(empty_25_reg_1426),
    .din3(grp_fu_1321_p3),
    .ce(1'b1),
    .dout(grp_fu_1321_p4)
);

depthwise_ama_addmuladd_14s_14ns_14s_14ns_14_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 14 ),
    .din3_WIDTH( 14 ),
    .dout_WIDTH( 14 ))
ama_addmuladd_14s_14ns_14s_14ns_14_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_1316_p2),
    .din1(grp_fu_1329_p1),
    .din2(empty_reg_1396),
    .din3(grp_fu_1329_p3),
    .ce(1'b1),
    .dout(grp_fu_1329_p4)
);

depthwise_mac_muladd_4s_4s_8ns_8_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 8 ))
mac_muladd_4s_4s_8ns_8_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(filter_V_q0),
    .din1(featureMap_V_q0),
    .din2(grp_fu_1339_p2),
    .ce(1'b1),
    .dout(grp_fu_1339_p3)
);

depthwise_ama_addmuladd_18ns_2ns_18s_18ns_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 18 ),
    .din3_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
ama_addmuladd_18ns_2ns_18s_18ns_18_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(trunc_ln109_reg_1606),
    .din1(grp_fu_1348_p1),
    .din2(empty_25_reg_1426),
    .din3(trunc_ln36_2_reg_1622),
    .ce(grp_fu_1348_ce),
    .dout(grp_fu_1348_p4)
);

depthwise_regslice_both #(
    .DataWidth( 32 ))
regslice_both_strm_in_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(strm_in_TDATA),
    .vld_in(strm_in_TVALID),
    .ack_in(regslice_both_strm_in_V_data_V_U_ack_in),
    .data_out(strm_in_TDATA_int_regslice),
    .vld_out(strm_in_TVALID_int_regslice),
    .ack_out(strm_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_strm_in_V_data_V_U_apdone_blk)
);

depthwise_regslice_both #(
    .DataWidth( 4 ))
regslice_both_strm_in_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(strm_in_TKEEP),
    .vld_in(strm_in_TVALID),
    .ack_in(regslice_both_strm_in_V_keep_V_U_ack_in),
    .data_out(strm_in_TKEEP_int_regslice),
    .vld_out(regslice_both_strm_in_V_keep_V_U_vld_out),
    .ack_out(strm_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_strm_in_V_keep_V_U_apdone_blk)
);

depthwise_regslice_both #(
    .DataWidth( 4 ))
regslice_both_strm_in_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(strm_in_TSTRB),
    .vld_in(strm_in_TVALID),
    .ack_in(regslice_both_strm_in_V_strb_V_U_ack_in),
    .data_out(strm_in_TSTRB_int_regslice),
    .vld_out(regslice_both_strm_in_V_strb_V_U_vld_out),
    .ack_out(strm_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_strm_in_V_strb_V_U_apdone_blk)
);

depthwise_regslice_both #(
    .DataWidth( 1 ))
regslice_both_strm_in_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(strm_in_TLAST),
    .vld_in(strm_in_TVALID),
    .ack_in(regslice_both_strm_in_V_last_V_U_ack_in),
    .data_out(strm_in_TLAST_int_regslice),
    .vld_out(regslice_both_strm_in_V_last_V_U_vld_out),
    .ack_out(strm_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_strm_in_V_last_V_U_apdone_blk)
);

depthwise_regslice_both #(
    .DataWidth( 32 ))
regslice_both_strm_out_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(strm_out_TDATA_int_regslice),
    .vld_in(strm_out_TVALID_int_regslice),
    .ack_in(strm_out_TREADY_int_regslice),
    .data_out(strm_out_TDATA),
    .vld_out(regslice_both_strm_out_V_data_V_U_vld_out),
    .ack_out(strm_out_TREADY),
    .apdone_blk(regslice_both_strm_out_V_data_V_U_apdone_blk)
);

depthwise_regslice_both #(
    .DataWidth( 4 ))
regslice_both_strm_out_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(strm_out_TVALID_int_regslice),
    .ack_in(regslice_both_strm_out_V_keep_V_U_ack_in_dummy),
    .data_out(strm_out_TKEEP),
    .vld_out(regslice_both_strm_out_V_keep_V_U_vld_out),
    .ack_out(strm_out_TREADY),
    .apdone_blk(regslice_both_strm_out_V_keep_V_U_apdone_blk)
);

depthwise_regslice_both #(
    .DataWidth( 4 ))
regslice_both_strm_out_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(strm_out_TVALID_int_regslice),
    .ack_in(regslice_both_strm_out_V_strb_V_U_ack_in_dummy),
    .data_out(strm_out_TSTRB),
    .vld_out(regslice_both_strm_out_V_strb_V_U_vld_out),
    .ack_out(strm_out_TREADY),
    .apdone_blk(regslice_both_strm_out_V_strb_V_U_apdone_blk)
);

depthwise_regslice_both #(
    .DataWidth( 1 ))
regslice_both_strm_out_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(strm_out_TVALID_int_regslice),
    .ack_in(regslice_both_strm_out_V_last_V_U_ack_in_dummy),
    .data_out(strm_out_TLAST),
    .vld_out(regslice_both_strm_out_V_last_V_U_vld_out),
    .ack_out(strm_out_TREADY),
    .apdone_blk(regslice_both_strm_out_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_condition_pp1_exit_iter0_state8))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((icmp_ln68_fu_972_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp1_exit_iter0_state8)) begin
                ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state8);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter5 <= ap_enable_reg_pp1_iter4;
        end else if (((icmp_ln68_fu_972_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_enable_reg_pp1_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state30) & (1'd0 == and_ln112_fu_1245_p2))) begin
        accum_V_fu_144 <= accum_V_4_fu_1227_p3;
    end else if ((~((1'b1 == ap_block_state33_io) | ((strm_out_TREADY_int_regslice == 1'b0) & (icmp_ln107_1_reg_1595 == 1'd1)) | ((strm_in_TVALID_int_regslice == 1'b0) & (icmp_ln113_reg_1677 == 1'd1))) & (1'b1 == ap_CS_fsm_state33) & (icmp_ln107_1_reg_1595 == 1'd1))) begin
        accum_V_fu_144 <= accum_V_7_fu_1286_p3;
    end else if ((~((1'b1 == ap_block_state33_io) | ((strm_out_TREADY_int_regslice == 1'b0) & (icmp_ln107_1_reg_1595 == 1'd1)) | ((strm_in_TVALID_int_regslice == 1'b0) & (icmp_ln113_reg_1677 == 1'd1))) & (1'b1 == ap_CS_fsm_state33) & (icmp_ln107_1_reg_1595 == 1'd0))) begin
        accum_V_fu_144 <= accum_V_4_reg_1666;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (strm_in_TVALID_int_regslice == 1'b1))) begin
        count_fu_132 <= 32'd0;
    end else if ((~((ap_predicate_op105_read_state4 == 1'b1) & (strm_in_TVALID_int_regslice == 1'b0)) & (icmp_ln56_fu_856_p2 == 1'd1) & (icmp_ln55_fu_851_p2 == 1'd1) & (icmp_ln54_fu_846_p2 == 1'd1) & (icmp_ln51_fu_840_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        count_fu_132 <= count_1_fu_869_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln97_fu_1089_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        kn_1_reg_548 <= kn_2_reg_595;
    end else if (((icmp_ln91_fu_1065_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        kn_1_reg_548 <= kn_reg_512;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state34_io) | ((ap_predicate_op328_write_state34 == 1'b1) & (strm_out_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_fsm_state34))) begin
        kn_2_reg_595 <= ap_phi_mux_kn_4_phi_fu_699_p16;
    end else if (((icmp_ln94_fu_1077_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        kn_2_reg_595 <= kn_1_reg_548;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln103_fu_1105_p2 == 1'd0) & (icmp_ln102_fu_1100_p2 == 1'd1) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        kn_4_reg_694 <= 32'd1536;
    end else if ((((icmp_ln105_fu_1115_p2 == 1'd0) & (icmp_ln104_fu_1110_p2 == 1'd1) & (icmp_ln103_fu_1105_p2 == 1'd1) & (icmp_ln102_fu_1100_p2 == 1'd1) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19)) | ((icmp_ln104_fu_1110_p2 == 1'd0) & (icmp_ln103_fu_1105_p2 == 1'd1) & (icmp_ln102_fu_1100_p2 == 1'd1) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19)) | ((icmp_ln102_fu_1100_p2 == 1'd0) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19)) | ((icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19)))) begin
        kn_4_reg_694 <= ap_phi_mux_kn_2_phi_fu_599_p4;
    end else if ((((1'b1 == ap_CS_fsm_state30) & (1'd0 == and_ln112_fu_1245_p2)) | (~((1'b1 == ap_block_state34_io) | ((ap_predicate_op328_write_state34 == 1'b1) & (strm_out_TREADY_int_regslice == 1'b0))) & (1'd1 == and_ln112_reg_1673) & (1'b1 == ap_CS_fsm_state34) & (icmp_ln105_reg_1591 == 1'd1) & (icmp_ln104_reg_1587 == 1'd1) & (icmp_ln103_reg_1583 == 1'd1) & (icmp_ln102_reg_1579 == 1'd1) & (icmp_ln101_reg_1575 == 1'd1) & (icmp_ln107_1_reg_1595 == 1'd1)) | (~((1'b1 == ap_block_state33_io) | ((strm_out_TREADY_int_regslice == 1'b0) & (icmp_ln107_1_reg_1595 == 1'd1)) | ((strm_in_TVALID_int_regslice == 1'b0) & (icmp_ln113_reg_1677 == 1'd1))) & (1'b1 == ap_CS_fsm_state33) & (icmp_ln107_1_reg_1595 == 1'd0)))) begin
        kn_4_reg_694 <= kn_2_reg_595;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln94_fu_1077_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        kn_reg_512 <= kn_3_fu_1083_p2;
    end else if (((icmp_ln89_fu_1053_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        kn_reg_512 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state30) & (1'd0 == and_ln112_fu_1245_p2))) begin
        kx_1_reg_759 <= kx_reg_618;
    end else if (((icmp_ln105_fu_1115_p2 == 1'd0) & (icmp_ln104_fu_1110_p2 == 1'd1) & (icmp_ln103_fu_1105_p2 == 1'd1) & (icmp_ln102_fu_1100_p2 == 1'd1) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        kx_1_reg_759 <= 32'd3;
    end else if ((((icmp_ln104_fu_1110_p2 == 1'd0) & (icmp_ln103_fu_1105_p2 == 1'd1) & (icmp_ln102_fu_1100_p2 == 1'd1) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19)) | ((icmp_ln103_fu_1105_p2 == 1'd0) & (icmp_ln102_fu_1100_p2 == 1'd1) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19)) | ((icmp_ln102_fu_1100_p2 == 1'd0) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19)) | ((icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19)))) begin
        kx_1_reg_759 <= ap_phi_mux_kx_phi_fu_622_p4;
    end else if (((~((1'b1 == ap_block_state34_io) | ((ap_predicate_op328_write_state34 == 1'b1) & (strm_out_TREADY_int_regslice == 1'b0))) & (1'd1 == and_ln112_reg_1673) & (1'b1 == ap_CS_fsm_state34) & (icmp_ln105_reg_1591 == 1'd1) & (icmp_ln104_reg_1587 == 1'd1) & (icmp_ln103_reg_1583 == 1'd1) & (icmp_ln102_reg_1579 == 1'd1) & (icmp_ln101_reg_1575 == 1'd1) & (icmp_ln107_1_reg_1595 == 1'd1)) | (~((1'b1 == ap_block_state33_io) | ((strm_out_TREADY_int_regslice == 1'b0) & (icmp_ln107_1_reg_1595 == 1'd1)) | ((strm_in_TVALID_int_regslice == 1'b0) & (icmp_ln113_reg_1677 == 1'd1))) & (1'b1 == ap_CS_fsm_state33) & (icmp_ln107_1_reg_1595 == 1'd0)))) begin
        kx_1_reg_759 <= 32'd2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state34_io) | ((ap_predicate_op328_write_state34 == 1'b1) & (strm_out_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_fsm_state34))) begin
        kx_reg_618 <= kx_2_fu_1303_p2;
    end else if (((icmp_ln94_fu_1077_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        kx_reg_618 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state34_io) | ((ap_predicate_op328_write_state34 == 1'b1) & (strm_out_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_fsm_state34))) begin
        ky_1_reg_607 <= ap_phi_mux_ky_3_phi_fu_732_p16;
    end else if (((icmp_ln94_fu_1077_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        ky_1_reg_607 <= ky_reg_559;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state30) & (1'd0 == and_ln112_fu_1245_p2))) begin
        ky_3_reg_726 <= ky_1_reg_607;
    end else if (((icmp_ln104_fu_1110_p2 == 1'd0) & (icmp_ln103_fu_1105_p2 == 1'd1) & (icmp_ln102_fu_1100_p2 == 1'd1) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        ky_3_reg_726 <= 32'd3;
    end else if ((((icmp_ln105_fu_1115_p2 == 1'd0) & (icmp_ln104_fu_1110_p2 == 1'd1) & (icmp_ln103_fu_1105_p2 == 1'd1) & (icmp_ln102_fu_1100_p2 == 1'd1) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19)) | ((icmp_ln103_fu_1105_p2 == 1'd0) & (icmp_ln102_fu_1100_p2 == 1'd1) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19)) | ((icmp_ln102_fu_1100_p2 == 1'd0) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19)) | ((icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19)))) begin
        ky_3_reg_726 <= ap_phi_mux_ky_1_phi_fu_610_p4;
    end else if (((~((1'b1 == ap_block_state34_io) | ((ap_predicate_op328_write_state34 == 1'b1) & (strm_out_TREADY_int_regslice == 1'b0))) & (1'd1 == and_ln112_reg_1673) & (1'b1 == ap_CS_fsm_state34) & (icmp_ln105_reg_1591 == 1'd1) & (icmp_ln104_reg_1587 == 1'd1) & (icmp_ln103_reg_1583 == 1'd1) & (icmp_ln102_reg_1579 == 1'd1) & (icmp_ln101_reg_1575 == 1'd1) & (icmp_ln107_1_reg_1595 == 1'd1)) | (~((1'b1 == ap_block_state33_io) | ((strm_out_TREADY_int_regslice == 1'b0) & (icmp_ln107_1_reg_1595 == 1'd1)) | ((strm_in_TVALID_int_regslice == 1'b0) & (icmp_ln113_reg_1677 == 1'd1))) & (1'b1 == ap_CS_fsm_state33) & (icmp_ln107_1_reg_1595 == 1'd0)))) begin
        ky_3_reg_726 <= 32'd2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln97_fu_1089_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        ky_reg_559 <= ky_2_fu_1130_p2;
    end else if (((icmp_ln91_fu_1065_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        ky_reg_559 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        n_1_reg_278 <= n_2_reg_311;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln47_fu_819_p2 == 1'd1))) begin
        n_1_reg_278 <= n_reg_254;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op105_read_state4 == 1'b1) & (strm_in_TVALID_int_regslice == 1'b0)) & (icmp_ln51_fu_840_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        n_2_reg_311 <= ap_phi_mux_n_3_phi_fu_363_p8;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_fu_828_p2 == 1'd1))) begin
        n_2_reg_311 <= n_1_reg_278;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln70_reg_1508 == 1'd1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        n_5_reg_412 <= n_7_reg_1525;
    end else if (((icmp_ln68_fu_972_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        n_5_reg_412 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_fu_828_p2 == 1'd0))) begin
        n_reg_254 <= n_4_fu_834_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (strm_in_TVALID_int_regslice == 1'b1))) begin
        n_reg_254 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln97_fu_1089_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        x_10_reg_536 <= x_11_reg_583;
    end else if (((icmp_ln91_fu_1065_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        x_10_reg_536 <= x_7_reg_501;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state34_io) | ((ap_predicate_op328_write_state34 == 1'b1) & (strm_out_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_fsm_state34))) begin
        x_11_reg_583 <= ap_phi_mux_x_12_phi_fu_667_p16;
    end else if (((icmp_ln94_fu_1077_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        x_11_reg_583 <= x_10_reg_536;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln102_fu_1100_p2 == 1'd0) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        x_12_reg_662 <= 32'd1024;
    end else if ((((icmp_ln105_fu_1115_p2 == 1'd0) & (icmp_ln104_fu_1110_p2 == 1'd1) & (icmp_ln103_fu_1105_p2 == 1'd1) & (icmp_ln102_fu_1100_p2 == 1'd1) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19)) | ((icmp_ln104_fu_1110_p2 == 1'd0) & (icmp_ln103_fu_1105_p2 == 1'd1) & (icmp_ln102_fu_1100_p2 == 1'd1) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19)) | ((icmp_ln103_fu_1105_p2 == 1'd0) & (icmp_ln102_fu_1100_p2 == 1'd1) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19)) | ((icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19)))) begin
        x_12_reg_662 <= ap_phi_mux_x_11_phi_fu_587_p4;
    end else if ((((1'b1 == ap_CS_fsm_state30) & (1'd0 == and_ln112_fu_1245_p2)) | (~((1'b1 == ap_block_state34_io) | ((ap_predicate_op328_write_state34 == 1'b1) & (strm_out_TREADY_int_regslice == 1'b0))) & (1'd1 == and_ln112_reg_1673) & (1'b1 == ap_CS_fsm_state34) & (icmp_ln105_reg_1591 == 1'd1) & (icmp_ln104_reg_1587 == 1'd1) & (icmp_ln103_reg_1583 == 1'd1) & (icmp_ln102_reg_1579 == 1'd1) & (icmp_ln101_reg_1575 == 1'd1) & (icmp_ln107_1_reg_1595 == 1'd1)) | (~((1'b1 == ap_block_state33_io) | ((strm_out_TREADY_int_regslice == 1'b0) & (icmp_ln107_1_reg_1595 == 1'd1)) | ((strm_in_TVALID_int_regslice == 1'b0) & (icmp_ln113_reg_1677 == 1'd1))) & (1'b1 == ap_CS_fsm_state33) & (icmp_ln107_1_reg_1595 == 1'd0)))) begin
        x_12_reg_662 <= x_11_reg_583;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        x_1_reg_389 <= x_5_fu_1021_p2;
    end else if (((icmp_ln67_fu_903_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        x_1_reg_389 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln91_fu_1065_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        x_2_reg_477 <= x_8_fu_1071_p2;
    end else if (((icmp_ln87_fu_1037_p2 == 1'd1) & (regslice_both_strm_out_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state15))) begin
        x_2_reg_477 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln70_reg_1508 == 1'd1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        x_4_reg_401 <= x_9_reg_424;
    end else if (((icmp_ln68_fu_972_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        x_4_reg_401 <= x_1_reg_389;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln94_fu_1077_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        x_7_reg_501 <= x_10_reg_536;
    end else if (((icmp_ln89_fu_1053_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        x_7_reg_501 <= x_2_reg_477;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln73_fu_984_p2 == 1'd0) & (icmp_ln70_fu_978_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        x_9_reg_424 <= 32'd1024;
    end else if ((((icmp_ln73_fu_984_p2 == 1'd1) & (icmp_ln70_fu_978_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln74_fu_989_p2 == 1'd0)) | ((icmp_ln73_fu_984_p2 == 1'd1) & (icmp_ln70_fu_978_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln74_fu_989_p2 == 1'd1)))) begin
        x_9_reg_424 <= ap_phi_mux_x_4_phi_fu_404_p4;
    end else if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        x_9_reg_424 <= ap_phi_reg_pp1_iter0_x_9_reg_424;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op105_read_state4 == 1'b1) & (strm_in_TVALID_int_regslice == 1'b0)) & (icmp_ln51_fu_840_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        x_reg_289 <= x_6_fu_885_p2;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_fu_828_p2 == 1'd1))) begin
        x_reg_289 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln97_fu_1089_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        y_10_reg_524 <= y_11_reg_571;
    end else if (((icmp_ln91_fu_1065_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        y_10_reg_524 <= y_9_reg_489;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state34_io) | ((ap_predicate_op328_write_state34 == 1'b1) & (strm_out_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_fsm_state34))) begin
        y_11_reg_571 <= ap_phi_mux_y_12_phi_fu_635_p16;
    end else if (((icmp_ln94_fu_1077_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        y_11_reg_571 <= y_10_reg_524;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln105_fu_1115_p2 == 1'd0) & (icmp_ln104_fu_1110_p2 == 1'd1) & (icmp_ln103_fu_1105_p2 == 1'd1) & (icmp_ln102_fu_1100_p2 == 1'd1) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19)) | ((icmp_ln104_fu_1110_p2 == 1'd0) & (icmp_ln103_fu_1105_p2 == 1'd1) & (icmp_ln102_fu_1100_p2 == 1'd1) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19)) | ((icmp_ln103_fu_1105_p2 == 1'd0) & (icmp_ln102_fu_1100_p2 == 1'd1) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19)) | ((icmp_ln102_fu_1100_p2 == 1'd0) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19)))) begin
        y_12_reg_630 <= ap_phi_mux_y_11_phi_fu_575_p4;
    end else if (((icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        y_12_reg_630 <= 32'd1024;
    end else if ((((1'b1 == ap_CS_fsm_state30) & (1'd0 == and_ln112_fu_1245_p2)) | (~((1'b1 == ap_block_state34_io) | ((ap_predicate_op328_write_state34 == 1'b1) & (strm_out_TREADY_int_regslice == 1'b0))) & (1'd1 == and_ln112_reg_1673) & (1'b1 == ap_CS_fsm_state34) & (icmp_ln105_reg_1591 == 1'd1) & (icmp_ln104_reg_1587 == 1'd1) & (icmp_ln103_reg_1583 == 1'd1) & (icmp_ln102_reg_1579 == 1'd1) & (icmp_ln101_reg_1575 == 1'd1) & (icmp_ln107_1_reg_1595 == 1'd1)) | (~((1'b1 == ap_block_state33_io) | ((strm_out_TREADY_int_regslice == 1'b0) & (icmp_ln107_1_reg_1595 == 1'd1)) | ((strm_in_TVALID_int_regslice == 1'b0) & (icmp_ln113_reg_1677 == 1'd1))) & (1'b1 == ap_CS_fsm_state33) & (icmp_ln107_1_reg_1595 == 1'd0)))) begin
        y_12_reg_630 <= y_11_reg_571;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op105_read_state4 == 1'b1) & (strm_in_TVALID_int_regslice == 1'b0)) & (icmp_ln51_fu_840_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        y_1_reg_300 <= ap_phi_mux_y_3_phi_fu_344_p8;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_fu_828_p2 == 1'd1))) begin
        y_1_reg_300 <= y_reg_266;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln47_fu_819_p2 == 1'd0))) begin
        y_2_reg_378 <= 2'd0;
    end else if (((icmp_ln68_fu_972_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        y_2_reg_378 <= y_6_reg_1464;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln89_fu_1053_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        y_4_reg_454 <= y_8_fu_1059_p2;
    end else if (((icmp_ln67_fu_903_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        y_4_reg_454 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln91_fu_1065_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        y_7_reg_466 <= y_9_reg_489;
    end else if (((icmp_ln87_fu_1037_p2 == 1'd1) & (regslice_both_strm_out_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state15))) begin
        y_7_reg_466 <= y_4_reg_454;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln94_fu_1077_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        y_9_reg_489 <= y_10_reg_524;
    end else if (((icmp_ln89_fu_1053_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        y_9_reg_489 <= y_7_reg_466;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        y_reg_266 <= y_5_fu_891_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln47_fu_819_p2 == 1'd1))) begin
        y_reg_266 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        accum_V_4_reg_1666 <= accum_V_4_fu_1227_p3;
        and_ln112_reg_1673 <= and_ln112_fu_1245_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln67_fu_903_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        accum_V_5_reg_1494 <= accum_V_5_fu_948_p1;
        conv48_reg_1484 <= conv48_fu_936_p1;
        conv59_reg_1489 <= conv59_fu_944_p1;
        sext_ln87_reg_1499 <= sext_ln87_fu_958_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state25) & (icmp_ln107_1_reg_1595 == 1'd1))) begin
        add_ln109_1_reg_1628 <= grp_fu_1321_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        empty_21_reg_1402 <= empty_21_fu_802_p1;
        empty_22_reg_1407 <= empty_22_fu_806_p1;
        empty_23_reg_1413 <= empty_23_fu_810_p1;
        empty_reg_1396 <= empty_fu_798_p1;
        tmp_data_V_reg_1418 <= strm_in_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln47_fu_819_p2 == 1'd0))) begin
        empty_25_reg_1426 <= empty_25_fu_825_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln74_reg_1516 == 1'd1) & (icmp_ln73_reg_1512 == 1'd1) & (icmp_ln70_reg_1508 == 1'd1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        empty_28_reg_1535 <= empty_28_fu_1013_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln97_fu_1089_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        icmp_ln101_reg_1575 <= icmp_ln101_fu_1095_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        icmp_ln102_reg_1579 <= icmp_ln102_fu_1100_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln102_fu_1100_p2 == 1'd1) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        icmp_ln103_reg_1583 <= icmp_ln103_fu_1105_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln103_fu_1105_p2 == 1'd1) & (icmp_ln102_fu_1100_p2 == 1'd1) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        icmp_ln104_reg_1587 <= icmp_ln104_fu_1110_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln104_fu_1110_p2 == 1'd1) & (icmp_ln103_fu_1105_p2 == 1'd1) & (icmp_ln102_fu_1100_p2 == 1'd1) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        icmp_ln105_reg_1591 <= icmp_ln105_fu_1115_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln105_fu_1115_p2 == 1'd1) & (icmp_ln104_fu_1110_p2 == 1'd1) & (icmp_ln103_fu_1105_p2 == 1'd1) & (icmp_ln102_fu_1100_p2 == 1'd1) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        icmp_ln107_1_reg_1595 <= icmp_ln107_1_fu_1120_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln112_fu_1245_p2) & (1'b1 == ap_CS_fsm_state30))) begin
        icmp_ln113_reg_1677 <= icmp_ln113_fu_1251_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        icmp_ln70_reg_1508 <= icmp_ln70_fu_978_p2;
        icmp_ln70_reg_1508_pp1_iter1_reg <= icmp_ln70_reg_1508;
        icmp_ln73_reg_1512_pp1_iter1_reg <= icmp_ln73_reg_1512;
        icmp_ln74_reg_1516_pp1_iter1_reg <= icmp_ln74_reg_1516;
        trunc_ln69_2_reg_1520_pp1_iter1_reg <= trunc_ln69_2_reg_1520;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp1_stage0_11001)) begin
        icmp_ln70_reg_1508_pp1_iter2_reg <= icmp_ln70_reg_1508_pp1_iter1_reg;
        icmp_ln70_reg_1508_pp1_iter3_reg <= icmp_ln70_reg_1508_pp1_iter2_reg;
        icmp_ln70_reg_1508_pp1_iter4_reg <= icmp_ln70_reg_1508_pp1_iter3_reg;
        icmp_ln73_reg_1512_pp1_iter2_reg <= icmp_ln73_reg_1512_pp1_iter1_reg;
        icmp_ln73_reg_1512_pp1_iter3_reg <= icmp_ln73_reg_1512_pp1_iter2_reg;
        icmp_ln73_reg_1512_pp1_iter4_reg <= icmp_ln73_reg_1512_pp1_iter3_reg;
        icmp_ln74_reg_1516_pp1_iter2_reg <= icmp_ln74_reg_1516_pp1_iter1_reg;
        icmp_ln74_reg_1516_pp1_iter3_reg <= icmp_ln74_reg_1516_pp1_iter2_reg;
        icmp_ln74_reg_1516_pp1_iter4_reg <= icmp_ln74_reg_1516_pp1_iter3_reg;
        trunc_ln69_2_reg_1520_pp1_iter2_reg <= trunc_ln69_2_reg_1520_pp1_iter1_reg;
        trunc_ln69_2_reg_1520_pp1_iter3_reg <= trunc_ln69_2_reg_1520_pp1_iter2_reg;
        trunc_ln69_2_reg_1520_pp1_iter4_reg <= trunc_ln69_2_reg_1520_pp1_iter3_reg;
        trunc_ln70_reg_1530_pp1_iter2_reg <= trunc_ln70_reg_1530;
        trunc_ln70_reg_1530_pp1_iter3_reg <= trunc_ln70_reg_1530_pp1_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln70_fu_978_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        icmp_ln73_reg_1512 <= icmp_ln73_fu_984_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln73_fu_984_p2 == 1'd1) & (icmp_ln70_fu_978_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        icmp_ln74_reg_1516 <= icmp_ln74_fu_989_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln70_fu_978_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        n_7_reg_1525 <= n_7_fu_1003_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        trunc_ln109_reg_1606 <= trunc_ln109_fu_1136_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        trunc_ln36_2_reg_1622 <= trunc_ln36_2_fu_1166_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        trunc_ln36_reg_1617 <= trunc_ln36_fu_1144_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln73_fu_984_p2 == 1'd1) & (icmp_ln70_fu_978_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln74_fu_989_p2 == 1'd1))) begin
        trunc_ln69_2_reg_1520 <= trunc_ln69_2_fu_994_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln70_reg_1508 == 1'd1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        trunc_ln70_reg_1530 <= trunc_ln70_fu_1009_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        y_6_reg_1464 <= y_6_fu_897_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln67_fu_903_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        zext_ln67_reg_1472[1 : 0] <= zext_ln67_fu_909_p1[1 : 0];
    end
end

always @ (*) begin
    if ((icmp_ln70_fu_978_p2 == 1'd0)) begin
        ap_condition_pp1_exit_iter0_state8 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state8 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter5 == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln112_reg_1673) & (1'b1 == ap_CS_fsm_state34) & (icmp_ln105_reg_1591 == 1'd1) & (icmp_ln104_reg_1587 == 1'd1) & (icmp_ln103_reg_1583 == 1'd1) & (icmp_ln102_reg_1579 == 1'd1) & (icmp_ln101_reg_1575 == 1'd1) & (icmp_ln107_1_reg_1595 == 1'd1))) begin
        ap_phi_mux_kn_4_phi_fu_699_p16 = kn_2_reg_595;
    end else begin
        ap_phi_mux_kn_4_phi_fu_699_p16 = kn_4_reg_694;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln112_reg_1673) & (1'b1 == ap_CS_fsm_state34) & (icmp_ln105_reg_1591 == 1'd1) & (icmp_ln104_reg_1587 == 1'd1) & (icmp_ln103_reg_1583 == 1'd1) & (icmp_ln102_reg_1579 == 1'd1) & (icmp_ln101_reg_1575 == 1'd1) & (icmp_ln107_1_reg_1595 == 1'd1))) begin
        ap_phi_mux_kx_1_phi_fu_764_p16 = 32'd2;
    end else begin
        ap_phi_mux_kx_1_phi_fu_764_p16 = kx_1_reg_759;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln112_reg_1673) & (1'b1 == ap_CS_fsm_state34) & (icmp_ln105_reg_1591 == 1'd1) & (icmp_ln104_reg_1587 == 1'd1) & (icmp_ln103_reg_1583 == 1'd1) & (icmp_ln102_reg_1579 == 1'd1) & (icmp_ln101_reg_1575 == 1'd1) & (icmp_ln107_1_reg_1595 == 1'd1))) begin
        ap_phi_mux_ky_3_phi_fu_732_p16 = 32'd2;
    end else begin
        ap_phi_mux_ky_3_phi_fu_732_p16 = ky_3_reg_726;
    end
end

always @ (*) begin
    if (((icmp_ln54_fu_846_p2 == 1'd0) & (icmp_ln51_fu_840_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_phi_mux_n_3_phi_fu_363_p8 = 32'd1536;
    end else if ((((icmp_ln56_fu_856_p2 == 1'd1) & (icmp_ln55_fu_851_p2 == 1'd1) & (icmp_ln54_fu_846_p2 == 1'd1) & (icmp_ln51_fu_840_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln56_fu_856_p2 == 1'd0) & (icmp_ln55_fu_851_p2 == 1'd1) & (icmp_ln54_fu_846_p2 == 1'd1) & (icmp_ln51_fu_840_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln55_fu_851_p2 == 1'd0) & (icmp_ln54_fu_846_p2 == 1'd1) & (icmp_ln51_fu_840_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        ap_phi_mux_n_3_phi_fu_363_p8 = n_2_reg_311;
    end else begin
        ap_phi_mux_n_3_phi_fu_363_p8 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln70_reg_1508 == 1'd1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_n_5_phi_fu_416_p4 = n_7_reg_1525;
    end else begin
        ap_phi_mux_n_5_phi_fu_416_p4 = n_5_reg_412;
    end
end

always @ (*) begin
    if (((icmp_ln73_fu_984_p2 == 1'd1) & (icmp_ln70_fu_978_p2 == 1'd1) & (icmp_ln74_fu_989_p2 == 1'd0))) begin
        ap_phi_mux_n_6_phi_fu_443_p6 = 32'd1536;
    end else if ((((icmp_ln73_fu_984_p2 == 1'd1) & (icmp_ln70_fu_978_p2 == 1'd1) & (icmp_ln74_fu_989_p2 == 1'd1)) | ((icmp_ln73_fu_984_p2 == 1'd0) & (icmp_ln70_fu_978_p2 == 1'd1)))) begin
        ap_phi_mux_n_6_phi_fu_443_p6 = ap_phi_mux_n_5_phi_fu_416_p4;
    end else begin
        ap_phi_mux_n_6_phi_fu_443_p6 = ap_phi_reg_pp1_iter0_n_6_reg_440;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln112_reg_1673) & (1'b1 == ap_CS_fsm_state34) & (icmp_ln105_reg_1591 == 1'd1) & (icmp_ln104_reg_1587 == 1'd1) & (icmp_ln103_reg_1583 == 1'd1) & (icmp_ln102_reg_1579 == 1'd1) & (icmp_ln101_reg_1575 == 1'd1) & (icmp_ln107_1_reg_1595 == 1'd1))) begin
        ap_phi_mux_x_12_phi_fu_667_p16 = x_11_reg_583;
    end else begin
        ap_phi_mux_x_12_phi_fu_667_p16 = x_12_reg_662;
    end
end

always @ (*) begin
    if (((icmp_ln56_fu_856_p2 == 1'd0) & (icmp_ln55_fu_851_p2 == 1'd1) & (icmp_ln54_fu_846_p2 == 1'd1) & (icmp_ln51_fu_840_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_phi_mux_x_3_phi_fu_326_p8 = 32'd3;
    end else if ((((icmp_ln56_fu_856_p2 == 1'd1) & (icmp_ln55_fu_851_p2 == 1'd1) & (icmp_ln54_fu_846_p2 == 1'd1) & (icmp_ln51_fu_840_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln55_fu_851_p2 == 1'd0) & (icmp_ln54_fu_846_p2 == 1'd1) & (icmp_ln51_fu_840_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln54_fu_846_p2 == 1'd0) & (icmp_ln51_fu_840_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        ap_phi_mux_x_3_phi_fu_326_p8 = x_reg_289;
    end else begin
        ap_phi_mux_x_3_phi_fu_326_p8 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln70_reg_1508 == 1'd1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_x_4_phi_fu_404_p4 = x_9_reg_424;
    end else begin
        ap_phi_mux_x_4_phi_fu_404_p4 = x_4_reg_401;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln112_reg_1673) & (1'b1 == ap_CS_fsm_state34) & (icmp_ln105_reg_1591 == 1'd1) & (icmp_ln104_reg_1587 == 1'd1) & (icmp_ln103_reg_1583 == 1'd1) & (icmp_ln102_reg_1579 == 1'd1) & (icmp_ln101_reg_1575 == 1'd1) & (icmp_ln107_1_reg_1595 == 1'd1))) begin
        ap_phi_mux_y_12_phi_fu_635_p16 = y_11_reg_571;
    end else begin
        ap_phi_mux_y_12_phi_fu_635_p16 = y_12_reg_630;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_851_p2 == 1'd0) & (icmp_ln54_fu_846_p2 == 1'd1) & (icmp_ln51_fu_840_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_phi_mux_y_3_phi_fu_344_p8 = 32'd3;
    end else if ((((icmp_ln56_fu_856_p2 == 1'd1) & (icmp_ln55_fu_851_p2 == 1'd1) & (icmp_ln54_fu_846_p2 == 1'd1) & (icmp_ln51_fu_840_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln56_fu_856_p2 == 1'd0) & (icmp_ln55_fu_851_p2 == 1'd1) & (icmp_ln54_fu_846_p2 == 1'd1) & (icmp_ln51_fu_840_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln54_fu_846_p2 == 1'd0) & (icmp_ln51_fu_840_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        ap_phi_mux_y_3_phi_fu_344_p8 = y_1_reg_300;
    end else begin
        ap_phi_mux_y_3_phi_fu_344_p8 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        featureMap_V_address0 = zext_ln116_fu_1270_p1;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        featureMap_V_address0 = zext_ln109_fu_1183_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter5 == 1'b1))) begin
        featureMap_V_address0 = zext_ln77_fu_1017_p1;
    end else begin
        featureMap_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter5 == 1'b1)) | (~((1'b1 == ap_block_state33_io) | ((strm_out_TREADY_int_regslice == 1'b0) & (icmp_ln107_1_reg_1595 == 1'd1)) | ((strm_in_TVALID_int_regslice == 1'b0) & (icmp_ln113_reg_1677 == 1'd1))) & (1'b1 == ap_CS_fsm_state33)))) begin
        featureMap_V_ce0 = 1'b1;
    end else begin
        featureMap_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        featureMap_V_d0 = trunc_ln69_fu_1265_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter5 == 1'b1))) begin
        featureMap_V_d0 = trunc_ln69_2_reg_1520_pp1_iter4_reg;
    end else begin
        featureMap_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter5 == 1'b1) & (icmp_ln74_reg_1516_pp1_iter4_reg == 1'd1) & (icmp_ln73_reg_1512_pp1_iter4_reg == 1'd1) & (icmp_ln70_reg_1508_pp1_iter4_reg == 1'd1)) | (~((1'b1 == ap_block_state33_io) | ((strm_out_TREADY_int_regslice == 1'b0) & (icmp_ln107_1_reg_1595 == 1'd1)) | ((strm_in_TVALID_int_regslice == 1'b0) & (icmp_ln113_reg_1677 == 1'd1))) & (1'b1 == ap_CS_fsm_state33) & (icmp_ln113_reg_1677 == 1'd1)))) begin
        featureMap_V_we0 = 1'b1;
    end else begin
        featureMap_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        filter_V_address0 = zext_ln109_1_fu_1188_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        filter_V_address0 = zext_ln59_fu_875_p1;
    end else begin
        filter_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | (~((ap_predicate_op105_read_state4 == 1'b1) & (strm_in_TVALID_int_regslice == 1'b0)) & (1'b1 == ap_CS_fsm_state4)))) begin
        filter_V_ce0 = 1'b1;
    end else begin
        filter_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_predicate_op105_read_state4 == 1'b1) & (strm_in_TVALID_int_regslice == 1'b0)) & (icmp_ln56_fu_856_p2 == 1'd1) & (icmp_ln55_fu_851_p2 == 1'd1) & (icmp_ln54_fu_846_p2 == 1'd1) & (icmp_ln51_fu_840_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        filter_V_we0 = 1'b1;
    end else begin
        filter_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        grp_fu_1309_ce = 1'b1;
    end else begin
        grp_fu_1309_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state31) | (~((1'b1 == ap_block_state33_io) | ((strm_out_TREADY_int_regslice == 1'b0) & (icmp_ln107_1_reg_1595 == 1'd1)) | ((strm_in_TVALID_int_regslice == 1'b0) & (icmp_ln113_reg_1677 == 1'd1))) & (1'b1 == ap_CS_fsm_state33)))) begin
        grp_fu_1348_ce = 1'b1;
    end else begin
        grp_fu_1348_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        grp_fu_998_ce = 1'b1;
    end else begin
        grp_fu_998_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | ((icmp_ln73_fu_984_p2 == 1'd1) & (icmp_ln70_fu_978_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln74_fu_989_p2 == 1'd1)) | ((icmp_ln56_fu_856_p2 == 1'd1) & (icmp_ln55_fu_851_p2 == 1'd1) & (icmp_ln54_fu_846_p2 == 1'd1) & (icmp_ln51_fu_840_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((1'b1 == ap_CS_fsm_state33) & (icmp_ln113_reg_1677 == 1'd1)))) begin
        strm_in_TDATA_blk_n = strm_in_TVALID_int_regslice;
    end else begin
        strm_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (strm_in_TVALID_int_regslice == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (ap_predicate_op158_read_state8 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | (~((1'b1 == ap_block_state33_io) | ((strm_out_TREADY_int_regslice == 1'b0) & (icmp_ln107_1_reg_1595 == 1'd1)) | ((strm_in_TVALID_int_regslice == 1'b0) & (icmp_ln113_reg_1677 == 1'd1))) & (1'b1 == ap_CS_fsm_state33) & (icmp_ln113_reg_1677 == 1'd1)) | (~((ap_predicate_op105_read_state4 == 1'b1) & (strm_in_TVALID_int_regslice == 1'b0)) & (1'b1 == ap_CS_fsm_state4) & (ap_predicate_op105_read_state4 == 1'b1)))) begin
        strm_in_TREADY_int_regslice = 1'b1;
    end else begin
        strm_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'd1 == and_ln112_reg_1673) & (1'b1 == ap_CS_fsm_state34) & (icmp_ln105_reg_1591 == 1'd1) & (icmp_ln104_reg_1587 == 1'd1) & (icmp_ln103_reg_1583 == 1'd1) & (icmp_ln102_reg_1579 == 1'd1) & (icmp_ln101_reg_1575 == 1'd1) & (icmp_ln107_1_reg_1595 == 1'd1)) | ((1'b1 == ap_CS_fsm_state33) & (icmp_ln107_1_reg_1595 == 1'd1)))) begin
        strm_out_TDATA_blk_n = strm_out_TREADY_int_regslice;
    end else begin
        strm_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state33_io) | ((strm_out_TREADY_int_regslice == 1'b0) & (icmp_ln107_1_reg_1595 == 1'd1)) | ((strm_in_TVALID_int_regslice == 1'b0) & (icmp_ln113_reg_1677 == 1'd1))) & (1'b1 == ap_CS_fsm_state33) & (icmp_ln107_1_reg_1595 == 1'd1))) begin
        strm_out_TVALID_int_regslice = 1'b1;
    end else begin
        strm_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (strm_in_TVALID_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln47_fu_819_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_fu_828_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~((ap_predicate_op105_read_state4 == 1'b1) & (strm_in_TVALID_int_regslice == 1'b0)) & (icmp_ln51_fu_840_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if ((~((ap_predicate_op105_read_state4 == 1'b1) & (strm_in_TVALID_int_regslice == 1'b0)) & (icmp_ln51_fu_840_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state6 : begin
            if (((icmp_ln67_fu_903_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((icmp_ln68_fu_972_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((icmp_ln70_fu_978_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0)) & ~((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter5 == 1'b1) & (ap_enable_reg_pp1_iter4 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if ((((icmp_ln70_fu_978_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0)) | ((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter5 == 1'b1) & (ap_enable_reg_pp1_iter4 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state15 : begin
            if (((icmp_ln87_fu_1037_p2 == 1'd0) & (regslice_both_strm_out_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((icmp_ln87_fu_1037_p2 == 1'd1) & (regslice_both_strm_out_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((icmp_ln89_fu_1053_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((icmp_ln91_fu_1065_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((icmp_ln94_fu_1077_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((icmp_ln97_fu_1089_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else if (((icmp_ln105_fu_1115_p2 == 1'd1) & (icmp_ln104_fu_1110_p2 == 1'd1) & (icmp_ln103_fu_1105_p2 == 1'd1) & (icmp_ln102_fu_1100_p2 == 1'd1) & (icmp_ln97_fu_1089_p2 == 1'd1) & (icmp_ln101_fu_1095_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            if (((1'd1 == and_ln112_fu_1245_p2) & (icmp_ln113_fu_1251_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state30))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else if (((1'd1 == and_ln112_fu_1245_p2) & (icmp_ln113_fu_1251_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state30))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            if ((~((1'b1 == ap_block_state33_io) | ((strm_out_TREADY_int_regslice == 1'b0) & (icmp_ln107_1_reg_1595 == 1'd1)) | ((strm_in_TVALID_int_regslice == 1'b0) & (icmp_ln113_reg_1677 == 1'd1))) & (1'b1 == ap_CS_fsm_state33))) begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end
        end
        ap_ST_fsm_state34 : begin
            if ((~((1'b1 == ap_block_state34_io) | ((ap_predicate_op328_write_state34 == 1'b1) & (strm_out_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_fsm_state34))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign accum_V_4_fu_1227_p3 = ((icmp_ln107_1_reg_1595[0:0] == 1'b1) ? grp_fu_1339_p3 : accum_V_fu_144);

assign accum_V_5_fu_948_p1 = $signed(bias_V_fu_913_p1);

assign accum_V_7_fu_1286_p3 = ((and_ln120_fu_1281_p2[0:0] == 1'b1) ? 8'd0 : accum_V_4_reg_1666);

assign add_ln109_2_fu_1178_p2 = ($signed(add_ln109_1_reg_1628) + $signed(trunc_ln36_3_fu_1174_p1));

assign add_ln109_fu_1152_p2 = (trunc_ln36_1_fu_1148_p1 + trunc_ln36_fu_1144_p1);

assign add_ln116_fu_1256_p2 = ($signed(trunc_ln36_reg_1617) + $signed(2'd3));

assign and_ln107_fu_1215_p2 = (icmp_ln107_fu_1209_p2 & icmp_ln107_1_reg_1595);

assign and_ln112_fu_1245_p2 = (icmp_ln112_fu_1233_p2 & icmp_ln112_1_fu_1239_p2);

assign and_ln120_fu_1281_p1 = relu;

assign and_ln120_fu_1281_p2 = (tmp_4_fu_1274_p3 & and_ln120_fu_1281_p1);

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_11001 = ((ap_enable_reg_pp1_iter0 == 1'b1) & (ap_predicate_op158_read_state8 == 1'b1) & (strm_in_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = ((ap_enable_reg_pp1_iter0 == 1'b1) & (ap_predicate_op158_read_state8 == 1'b1) & (strm_in_TVALID_int_regslice == 1'b0));
end

assign ap_block_state10_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp1_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp1_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp1_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state33 = (((strm_out_TREADY_int_regslice == 1'b0) & (icmp_ln107_1_reg_1595 == 1'd1)) | ((strm_in_TVALID_int_regslice == 1'b0) & (icmp_ln113_reg_1677 == 1'd1)));
end

always @ (*) begin
    ap_block_state33_io = ((strm_out_TREADY_int_regslice == 1'b0) & (icmp_ln107_1_reg_1595 == 1'd1));
end

always @ (*) begin
    ap_block_state34 = ((ap_predicate_op328_write_state34 == 1'b1) & (strm_out_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state34_io = ((ap_predicate_op328_write_state34 == 1'b1) & (strm_out_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state4 = ((ap_predicate_op105_read_state4 == 1'b1) & (strm_in_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state8_pp1_stage0_iter0 = ((ap_predicate_op158_read_state8 == 1'b1) & (strm_in_TVALID_int_regslice == 1'b0));
end

assign ap_block_state9_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_phi_mux_kn_2_phi_fu_599_p4 = kn_2_reg_595;

assign ap_phi_mux_kx_phi_fu_622_p4 = kx_reg_618;

assign ap_phi_mux_ky_1_phi_fu_610_p4 = ky_1_reg_607;

assign ap_phi_mux_x_11_phi_fu_587_p4 = x_11_reg_583;

assign ap_phi_mux_y_11_phi_fu_575_p4 = y_11_reg_571;

assign ap_phi_reg_pp1_iter0_n_6_reg_440 = 'bx;

assign ap_phi_reg_pp1_iter0_x_9_reg_424 = 'bx;

always @ (*) begin
    ap_predicate_op105_read_state4 = ((icmp_ln56_fu_856_p2 == 1'd1) & (icmp_ln55_fu_851_p2 == 1'd1) & (icmp_ln54_fu_846_p2 == 1'd1) & (icmp_ln51_fu_840_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op158_read_state8 = ((icmp_ln73_fu_984_p2 == 1'd1) & (icmp_ln70_fu_978_p2 == 1'd1) & (icmp_ln74_fu_989_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op328_write_state34 = ((1'd1 == and_ln112_reg_1673) & (icmp_ln105_reg_1591 == 1'd1) & (icmp_ln104_reg_1587 == 1'd1) & (icmp_ln103_reg_1583 == 1'd1) & (icmp_ln102_reg_1579 == 1'd1) & (icmp_ln101_reg_1575 == 1'd1) & (icmp_ln107_1_reg_1595 == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bias_V_fu_913_p1 = tmp_data_V_reg_1418[3:0];

assign conv48_fu_936_p1 = outMapYSize_fu_920_p2;

assign conv59_fu_944_p1 = $signed(outMapXSize_fu_930_p2);

assign count_1_fu_869_p2 = (count_fu_132 + 32'd1);

assign empty_21_fu_802_p1 = mapSizeX[15:0];

assign empty_22_fu_806_p1 = kernelSize[15:0];

assign empty_23_fu_810_p0 = mapSizeY;

assign empty_23_fu_810_p1 = empty_23_fu_810_p0[15:0];

assign empty_25_fu_825_p1 = mapSizeX[17:0];

assign empty_28_fu_1013_p1 = grp_fu_998_p2[17:0];

assign empty_fu_798_p1 = kernelSize[13:0];

assign filter_V_d0 = strm_in_TDATA_int_regslice[3:0];

assign grp_fu_1309_p1 = zext_ln67_reg_1472;

assign grp_fu_1316_p0 = kn_2_reg_595[13:0];

assign grp_fu_1321_p0 = grp_fu_1321_p00;

assign grp_fu_1321_p00 = add_ln109_fu_1152_p2;

assign grp_fu_1321_p3 = x_11_reg_583[17:0];

assign grp_fu_1329_p1 = ky_1_reg_607[13:0];

assign grp_fu_1329_p3 = kx_reg_618[13:0];

assign grp_fu_1339_p2 = ((and_ln107_fu_1215_p2[0:0] == 1'b1) ? accum_V_5_reg_1494 : accum_V_fu_144);

assign grp_fu_1348_p1 = grp_fu_1348_p10;

assign grp_fu_1348_p10 = add_ln116_fu_1256_p2;

assign icmp_ln101_fu_1095_p2 = (($signed(y_11_reg_571) < $signed(conv48_reg_1484)) ? 1'b1 : 1'b0);

assign icmp_ln102_fu_1100_p2 = (($signed(x_11_reg_583) < $signed(mapSizeX)) ? 1'b1 : 1'b0);

assign icmp_ln103_fu_1105_p2 = (($signed(kn_2_reg_595) < $signed(kernelN)) ? 1'b1 : 1'b0);

assign icmp_ln104_fu_1110_p2 = (($signed(ky_1_reg_607) < $signed(kernelSize)) ? 1'b1 : 1'b0);

assign icmp_ln105_fu_1115_p2 = (($signed(kx_reg_618) < $signed(kernelSize)) ? 1'b1 : 1'b0);

assign icmp_ln107_1_fu_1120_p2 = (($signed(x_11_reg_583) < $signed(conv59_reg_1489)) ? 1'b1 : 1'b0);

assign icmp_ln107_fu_1209_p2 = ((or_ln107_fu_1203_p2 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln112_1_fu_1239_p2 = ((kx_reg_618 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln112_fu_1233_p2 = ((ky_1_reg_607 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln113_fu_1251_p2 = (($signed(y_11_reg_571) < $signed(sext_ln87_reg_1499)) ? 1'b1 : 1'b0);

assign icmp_ln47_fu_819_p2 = (($signed(n_reg_254) < $signed(32'd1536)) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_828_p2 = (($signed(y_reg_266) < $signed(32'd3)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_840_p2 = (($signed(x_reg_289) < $signed(32'd3)) ? 1'b1 : 1'b0);

assign icmp_ln54_fu_846_p2 = (($signed(n_2_reg_311) < $signed(kernelN)) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_851_p2 = (($signed(y_1_reg_300) < $signed(kernelSize)) ? 1'b1 : 1'b0);

assign icmp_ln56_fu_856_p2 = (($signed(x_reg_289) < $signed(kernelSize)) ? 1'b1 : 1'b0);

assign icmp_ln67_fu_903_p2 = ((y_2_reg_378 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_972_p2 = (($signed(tmp_2_fu_962_p4) < $signed(22'd1)) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_978_p2 = (($signed(ap_phi_mux_n_5_phi_fu_416_p4) < $signed(32'd1536)) ? 1'b1 : 1'b0);

assign icmp_ln73_fu_984_p2 = (($signed(ap_phi_mux_x_4_phi_fu_404_p4) < $signed(mapSizeX)) ? 1'b1 : 1'b0);

assign icmp_ln74_fu_989_p2 = (($signed(ap_phi_mux_n_5_phi_fu_416_p4) < $signed(kernelN)) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_1037_p2 = (($signed(tmp_1_fu_1027_p4) < $signed(22'd1)) ? 1'b1 : 1'b0);

assign icmp_ln89_fu_1053_p2 = (($signed(tmp_3_fu_1043_p4) < $signed(22'd1)) ? 1'b1 : 1'b0);

assign icmp_ln91_fu_1065_p2 = (($signed(kn_reg_512) < $signed(32'd1536)) ? 1'b1 : 1'b0);

assign icmp_ln94_fu_1077_p2 = (($signed(ky_reg_559) < $signed(32'd3)) ? 1'b1 : 1'b0);

assign icmp_ln97_fu_1089_p2 = (($signed(kx_reg_618) < $signed(32'd3)) ? 1'b1 : 1'b0);

assign kn_3_fu_1083_p2 = (kn_1_reg_548 + 32'd1);

assign kx_2_fu_1303_p2 = (ap_phi_mux_kx_1_phi_fu_764_p16 + 32'd1);

assign ky_2_fu_1130_p2 = (ky_1_reg_607 + 32'd1);

assign n_4_fu_834_p2 = (n_1_reg_278 + 32'd1);

assign n_7_fu_1003_p2 = (ap_phi_mux_n_6_phi_fu_443_p6 + 32'd1);

assign or_ln107_fu_1203_p2 = (ky_1_reg_607 | kx_reg_618);

assign outMapXSize_fu_930_p2 = (sub_ln85_fu_926_p2 + 16'd1);

assign outMapYSize_cast_fu_940_p1 = outMapYSize_fu_920_p2;

assign outMapYSize_fu_920_p2 = (sub_ln84_fu_916_p2 + 16'd1);

assign sext_ln87_fu_958_p1 = $signed(sub81_fu_952_p2);

assign strm_in_TREADY = regslice_both_strm_in_V_data_V_U_ack_in;

assign strm_out_TDATA_int_regslice = $signed(accum_V_7_fu_1286_p3);

assign strm_out_TVALID = regslice_both_strm_out_V_data_V_U_vld_out;

assign sub81_fu_952_p2 = ($signed(outMapYSize_cast_fu_940_p1) + $signed(17'd131071));

assign sub_ln84_fu_916_p2 = (empty_23_reg_1413 - empty_22_reg_1407);

assign sub_ln85_fu_926_p2 = (empty_21_reg_1402 - empty_22_reg_1407);

assign tmp_1_fu_1027_p4 = {{y_4_reg_454[31:10]}};

assign tmp_2_fu_962_p4 = {{x_1_reg_389[31:10]}};

assign tmp_3_fu_1043_p4 = {{x_2_reg_477[31:10]}};

assign tmp_4_fu_1274_p3 = accum_V_4_reg_1666[32'd7];

assign trunc_ln109_fu_1136_p1 = grp_fu_1125_p2[17:0];

assign trunc_ln36_1_fu_1148_p1 = ky_1_reg_607[1:0];

assign trunc_ln36_2_fu_1166_p1 = x_11_reg_583[17:0];

assign trunc_ln36_3_fu_1174_p1 = kx_reg_618[17:0];

assign trunc_ln36_fu_1144_p1 = y_11_reg_571[1:0];

assign trunc_ln69_2_fu_994_p1 = strm_in_TDATA_int_regslice[3:0];

assign trunc_ln69_fu_1265_p1 = strm_in_TDATA_int_regslice[3:0];

assign trunc_ln70_fu_1009_p1 = x_4_reg_401[17:0];

assign x_5_fu_1021_p2 = (x_4_reg_401 + 32'd1);

assign x_6_fu_885_p2 = (ap_phi_mux_x_3_phi_fu_326_p8 + 32'd1);

assign x_8_fu_1071_p2 = (x_7_reg_501 + 32'd1);

assign y_5_fu_891_p2 = (y_1_reg_300 + 32'd1);

assign y_6_fu_897_p2 = (y_2_reg_378 + 2'd1);

assign y_8_fu_1059_p2 = (y_7_reg_466 + 32'd1);

assign zext_ln109_1_fu_1188_p1 = $unsigned(grp_fu_1329_p4);

assign zext_ln109_fu_1183_p1 = add_ln109_2_fu_1178_p2;

assign zext_ln116_fu_1270_p1 = $unsigned(grp_fu_1348_p4);

assign zext_ln59_fu_875_p1 = count_fu_132;

assign zext_ln67_fu_909_p1 = y_2_reg_378;

assign zext_ln77_fu_1017_p1 = $unsigned(grp_fu_1309_p4);

always @ (posedge ap_clk) begin
    zext_ln67_reg_1472[17:2] <= 16'b0000000000000000;
end

endmodule //depthwise
